[package]
name = "rpgmvmz-decrypter-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "decvz"
path = "src/main.rs"

[dependencies]
rpgmvmz-decrypter = { path = "../lib", version = "0.1.0", features = [
  "filesystem",
] }
